### ISSUE TITLE
CA certificates bundle needed?

### ISSUE THREAD

**Issue by cimm** [jamesgolick/always_verify_ssl_certificates#7]
The [RubyInside artcile](http://www.rubyinside.com/how-to-cure-nethttps-risky-default-https-behavior-4010.html) mentions the CA certificates bundle:

```
To get going, you need a local CA certificates bundle, the official 
curl site maintains an up to date cacert.pem / ca-bundle.crt file containing
all of the major certificates if you need one.
```

 The README does not. This confuses me, do I need the CA certificates bundle or will the gem does it job without it? Thanks!

**Comment by Shelvetco** [comment]
Some OSs include the certificate bundle as part of the system. If this is the case, you're all good to go. If not, you do need it. Without it, this gem will raise on any https connection

**Comment by cimm** [comment]
@Shelvetco I no longer remember posting this question but thank you for the clarification. ;)
